INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('0', 'classical poem','Author: Pushkin',100 );
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('1', 'poems','Author: Lermontov',200);
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('2', 'novel','Author: B',400);
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('3', 'story','Author: C',500);
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('4', 'detective','Author: D',700);
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('5', 'horror','Author: E',600);
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('6', 'mystic','Author: F',900);
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('7', 'satire','Author: G',800);
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('8', 'adventure','Author: H',1000);
INSERT INTO `webstore`.`products` (`id`, `pname`, `productDescription`, `cost`) VALUES ('9', 'hokku','Author: J',1100);